# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

config.vm.define "server" do |server|
server.vm.box = "bento/ubuntu-20.04"
server.vm.box_check_update = false
server.vm.hostname = "server"
server.vm.network "private_network", ip: "192.168.56.10"

server.vm.synced_folder ".", "/vagrant"

server.vm.provider "virtualbox" do |vb|
vb.gui = false
vb.memory = "1024"
end
server.vm.provision "shell", path:"script/server-provision.sh"
end

config.vm.define "client" do |client|
client.vm.box = "alvistack/ubuntu-20.04"
client.vm.box_check_update = false
client.vm.hostname = "client"
client.vm.network "private_network", ip: "192.168.56.11"

client.vm.synced_folder ".", "/vagrant"

client.vm.provider "virtualbox" do |vb|
vb.gui = false
vb.memory = "1024"
end
client.vm.provision "shell", path:"script/client-provision.sh"
end


end
