apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress-dev.fullname" . }}-mysql-config
  namespace: {{ .Release.Namespace }}
data:
  MYSQL_DATABASE: {{ .Values.mysql.credentials.database }}
  MYSQL_USER: {{ .Values.mysql.credentials.user }}
