apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-dev.fullname" . }}-mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.mysql.credentials.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.credentials.rootPassword | b64enc }}
