apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-dev.fullname" . }}-mysql-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-dev.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.port.servicePort }}
      targetPort: {{ .Values.mysql.port.containerPort }}
  selector:
    app.kubernetes.io/name: {{ include "wordpress-dev.name" . }}
    app.kubernetes.io/component: mysql
