apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-dev.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.mysql.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
