apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-dev.fullname" . }}-wordpress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-dev.labels" . | nindent 4 }}
spec:
  type: ClusterIP #NodePort
  ports:
    - port: 80
      targetPort: 80
      #nodePort: 30081
  selector:
    app.kubernetes.io/name: {{ include "wordpress-dev.name" . }}
    app.kubernetes.io/component: wordpress
