apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-dev.fullname" . }}-wordpress-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.credentials.dbPassword }}
