# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

config.vm.define "dev" do |dev|
dev.vm.box = "bento/ubuntu-20.04"
dev.vm.box_check_update = false
dev.vm.hostname = "dev"
dev.vm.network "private_network", ip: "192.168.56.10"

dev.vm.synced_folder ".", "/vagrant"

dev.vm.provider "virtualbox" do |vb|
vb.gui = false
vb.memory = "1024"
end
dev.vm.provision "shell", path:"script/dev-provision.sh"
end

config.vm.define "prod" do |prod|
prod.vm.box = "alvistack/ubuntu-20.04"
prod.vm.box_check_update = false
prod.vm.hostname = "prod"
prod.vm.network "private_network", ip: "192.168.56.11"

prod.vm.synced_folder ".", "/vagrant"

prod.vm.provider "virtualbox" do |vb|
vb.gui = false
vb.memory = "1024"
end
prod.vm.provision "shell", path:"script/prod-provision.sh"
end


end
