# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

config.vm.define "server" do |server|
server.vm.box = "bento/ubuntu-20.04"
server.vm.box_check_update = false
server.vm.hostname = "server"
server.vm.network "private_network", ip: "192.168.56.10"
server.vm.provider "virtualbox" do |vb|
vb.gui = false
vb.memory = "1024"
end

server.vm.provision "shell", inline: <<-SHELL
sudo apt-get install -y openssh-server
sudo systemctl enable ssh
sudo systemctl start ssh
mkdir -p ~/.ssh
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys
SHELL

end

config.vm.define "client" do |client|
client.vm.box = "alvistack/ubuntu-20.04"
client.vm.box_check_update = false
client.vm.hostname = "client"
client.vm.network "private_network", ip: "192.168.56.11"
client.vm.provider "virtualbox" do |vb|
vb.gui = false
vb.memory = "1024"
end
client.vm.provision "shell", path:"script/new.sh"

end

end
